# Generated by Django 4.0.2 on 2022-07-04 01:59

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0003_blog_category_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField(null=True)),
                ('discription', djrichtextfield.models.RichTextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(auto_now=True)),
                ('categorys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zapp.blog_category')),
            ],
        ),
    ]
