# Generated by Django 4.0.2 on 2022-07-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0004_story_category_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_category',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
