# Generated by Django 4.0.2 on 2022-07-04 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0006_story_category_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zapp.story_category'),
        ),
    ]
