# Generated by Django 4.0.6 on 2022-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0007_alter_story_categorys'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quction', models.CharField(max_length=50, null=True)),
                ('answer', models.TextField(null=True)),
            ],
        ),
    ]
