# Generated by Django 4.0.6 on 2022-07-30 15:56

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0008_faqss'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesOfChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField(null=True)),
                ('discription', djrichtextfield.models.RichTextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
